//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public System.Guid OrderItemGuid { get; set; }
        public int OrderId { get; set; }
        public long ProductId { get; set; }
        public int Quantity { get; set; }
        public string AttributeDescription { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
        public decimal ProductCost { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual product product { get; set; }
    }
}
